services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=truef
    ports:
      - "3000:3000"
    command: npm start

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
